In [166]:
import numpy as np
from PIL import Image

In [186]:
def transform_log( I , const):
    logArray = I + 1
    logArray = np.log(logArray)
    logImg = Image.fromarray( np.uint8( logArray * 255 ) ).convert( "RGB" )
    logImg = Image.eval(logImg, (lambda x: x * const))
    logArray = np.array( logImg ) / 255
    #print(logArray)
    return logArray

In [189]:
def ler_imagem( caminho ):
    return np.array( Image.open( caminho ) ) / 255

def mostrar_imagem( img ):
    img_mostrar = Image.fromarray( np.uint8( img * 255 ) ).convert( "RGB" )
    img_mostrar.show()

def salvar_imagem( img, caminho, formato ):
    img_salvar = Image.fromarray( np.uint8( img * 255 ) ).convert( "RGB" )
    img_salvar.save( caminho, formato )

In [191]:
imagem = ler_imagem( "Imagens/Pinguim_1.jpg" )

imagem_log = transform_log(imagem, 1)
imagens_juntas = np.hstack( ( imagem, imagem_log ) )

mostrar_imagem( imagens_juntas)

[[[0.60392157 0.62745098 0.65882353]
  [0.60392157 0.62745098 0.65882353]
  [0.60392157 0.62745098 0.65882353]
  ...
  [0.60784314 0.62745098 0.6627451 ]
  [0.60784314 0.62745098 0.6627451 ]
  [0.60784314 0.62745098 0.6627451 ]]

 [[0.60392157 0.62745098 0.65882353]
  [0.60392157 0.62745098 0.65882353]
  [0.60392157 0.62745098 0.65882353]
  ...
  [0.60784314 0.62745098 0.6627451 ]
  [0.60784314 0.62745098 0.6627451 ]
  [0.60784314 0.62745098 0.6627451 ]]

 [[0.60392157 0.62745098 0.65882353]
  [0.60392157 0.62745098 0.65882353]
  [0.60392157 0.62745098 0.65882353]
  ...
  [0.60392157 0.62745098 0.6627451 ]
  [0.60392157 0.62745098 0.6627451 ]
  [0.60392157 0.62745098 0.6627451 ]]

 ...

 [[0.26666667 0.27058824 0.30980392]
  [0.28235294 0.29019608 0.32156863]
  [0.31372549 0.32156863 0.34509804]
  ...
  [0.01176471 0.         0.01176471]
  [0.01176471 0.         0.01176471]
  [0.01960784 0.         0.01176471]]

 [[0.25490196 0.2627451  0.30588235]
  [0.2745098  0.27843137 0.31764706]


In [192]:
salvar_imagem( imagens_juntas, "Imagens/Pinguins_normais_e_negativos.jpg", 'JPEG' )